/************************************************************************************
 * Module      : Ultrasonic Driver
 * File Name   : ultrasonic.h
 * Author      : Mahmoud 3smat
 * Created on  : 8/10/2024
 * Description : Header file for the Ultrasonic Driver
 ************************************************************************************/
#ifndef HAL_ULTRASONIC_ULTRASONIC_H_
#define HAL_ULTRASONIC_ULTRASONIC_H_

#include "../../LIB/common_macros.h"
#include "../../MCAL/GPIO/gpio.h"
#include "../../LIB/std_types.h"
#include "../../MCAL/ICU/icu.h"
#include <util/delay.h>

#define ULTRASONIC_TRIG_PORT_ID			PORTD_ID
#define ULTRASONIC_TRIG_PIN_ID			PIN7_ID

#define ULTRASONIC_ECHO_PORT_ID			PORTD_ID
#define ULTRASONIC_ECHO_PIN_ID			PIN6_ID

/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/
/*
 * Description: Function to initialize the Ultrasonic Driver
 * 	- Initialize the ICU driver as required.
 * 	- Set up the ICU callback function.
 * 	- Set the direction for the trigger pin as output through the GPIO driver.
 */
void Ultrasonic_init(void);

/*
 * Description: Function to send the trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void);

/*
 * Description: Function to read the distance measured by the ultrasonic sensor.
 * 	- Sends a trigger pulse by using the Ultrasonic_Trigger function.
 * 	- Starts the measurement process via the ICU driver.
 * 	- Return: The measured distance in centimeters.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description: Callback function called by the ICU driver.
 * 	- This function calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* HAL_ULTRASONIC_ULTRASONIC_H_ */
